// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: P2P/P2P.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	P2P_BootstrapConnect_FullMethodName = "/P2P.P2P/BootstrapConnect"
)

// P2PClient is the client API for P2P service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type P2PClient interface {
	BootstrapConnect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BootClient, BootServer], error)
}

type p2PClient struct {
	cc grpc.ClientConnInterface
}

func NewP2PClient(cc grpc.ClientConnInterface) P2PClient {
	return &p2PClient{cc}
}

func (c *p2PClient) BootstrapConnect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BootClient, BootServer], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &P2P_ServiceDesc.Streams[0], P2P_BootstrapConnect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BootClient, BootServer]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type P2P_BootstrapConnectClient = grpc.BidiStreamingClient[BootClient, BootServer]

// P2PServer is the server API for P2P service.
// All implementations must embed UnimplementedP2PServer
// for forward compatibility.
type P2PServer interface {
	BootstrapConnect(grpc.BidiStreamingServer[BootClient, BootServer]) error
	mustEmbedUnimplementedP2PServer()
}

// UnimplementedP2PServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedP2PServer struct{}

func (UnimplementedP2PServer) BootstrapConnect(grpc.BidiStreamingServer[BootClient, BootServer]) error {
	return status.Errorf(codes.Unimplemented, "method BootstrapConnect not implemented")
}
func (UnimplementedP2PServer) mustEmbedUnimplementedP2PServer() {}
func (UnimplementedP2PServer) testEmbeddedByValue()             {}

// UnsafeP2PServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to P2PServer will
// result in compilation errors.
type UnsafeP2PServer interface {
	mustEmbedUnimplementedP2PServer()
}

func RegisterP2PServer(s grpc.ServiceRegistrar, srv P2PServer) {
	// If the following call pancis, it indicates UnimplementedP2PServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&P2P_ServiceDesc, srv)
}

func _P2P_BootstrapConnect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(P2PServer).BootstrapConnect(&grpc.GenericServerStream[BootClient, BootServer]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type P2P_BootstrapConnectServer = grpc.BidiStreamingServer[BootClient, BootServer]

// P2P_ServiceDesc is the grpc.ServiceDesc for P2P service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var P2P_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "P2P.P2P",
	HandlerType: (*P2PServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BootstrapConnect",
			Handler:       _P2P_BootstrapConnect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "P2P/P2P.proto",
}
